language: python

python:
  - 2.7

env:
  - DISABLE_NOTIFIER=true

libraries:
  - name: pycrypto
    version: "2.6"

install:
  # Upgrade node.js
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs

  - npm install gulp --global
  - npm install gulp --save-dev
  - npm install
  - npm install -g markdown-link-check

  - pip install "pip>=1.5.6"
  - pip install "pycrypto>=2.6"
  - pip install requests pyOpenSSL ndg-httpsclient pyasn1
  - pip install docutils
  - pip install -r submission-form-scripts/requirements.txt

script:
  - gulp clean
  - gulp styles
  - gulp scripts

  # Python unit tests
  - python submission-form-scripts/test_botsheeter.py
  # Error and style-checker
  - flake8 submission-form-scripts/*.py

  # Cat all the .md files into a single, big file and then check links
  - find content/ -name '*.md' -exec cat {} \; > /tmp/all-the-markdown.md
  - node --version
  - markdown-link-check /tmp/all-the-markdown.md
